import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
   "en": {
     "Login": "Login",
     "user name":"User Name",
     "Password":"Password",
     "Action":"Action",
     "Pickup":"Pickup",
     "Working":"Working",
     "Delivery":"Delivery",
     "Complete":"Complete",
     "Phone Number":"Phone Number",
     "forget your password?":"Forget Your Password ?",
     "don/'t have an account ?":"don/'t have an account ?",
     "Signup":"Signup",
     "Complete your data":"Complete your data",
     "Choose Country":"Choose Country",
     "Help & Settings":"Help & Settings",
     "Email Address":"Email Address",
     "Confirm Password":"Confirm Password",
     "Select a country":"Select a country",
     "already have an account ?":"already have an account ?",
     "Signin":"SignIn",
     "Get Verification Code":"Get Verification Code",
     "Enter Verification Code":"Enter Verification Code",
     "Next Step":"Next Step",
     "Home":"Home",
     "Cart":"Cart",
     "Products":"Products",
     "About":"About",
     "Settings":"Settings",
     "Tracking":"Tracking",
     "Name":"Name",
     "Email":"Email",
     "Language": "Language",
     "English": "English",
     "Arabic": "Arabic",
     "Logout":"Logout",
     "Save":"Save",



     "Categories" :"Categories ",
     "We Care About Your House" : " We Care About your House ",
     "All Categories" : "All Categories",
     "Full name" : "Full Name",
     "Age" : "Age",
     "Country":"Country",
     "Address" :"Address",
     "Gender" :"Gender",
     "Male" :"Male",
     "Female":"Female",
     "Cancel":"Cancel",
     "Done" :"Done" ,
     "Add":"Add",
     "Please Wait Loading" :"Please Wait Loading...",
     "Hello  ": "Hello",
     "Client": "Client",
     "Your Profile" :"Your Profile",
     "Your Security Information" : "Your Security Information",

     "Change Language" : "Change Language",
     "Profile": "Profile",
     "My Orders" : "My Orders",
     "Update" : "Update"
   },
    "ar":{
      "Login": "تسجيل الدخول",
      "user name":"اسم المستخدم",
      "Password":"كلمة المرور",
      "forget your password?":"هل نسيت كلمة المرور ؟",
      "don't have an account ?":"ليس لديك حساب ؟",
      "Signup":"انشاء حساب جديد",
      "Action":"قيد الإنتظار",
      "Pickup":"إستلام",
      "Working":"جاري",
      "Delivery":"توصيل",
      "Complete":"منتهية",
      "Choose Country":"اختيار الدولة",
      "Phone Number":"رقم الموبايل",
      "Help & Settings":"المساعدة والإعدادات",
      "Email Address":"البريد الإلكتروني",
      "Confirm Password":"تأكيد كلمة المرور",
      "Select a country":"اختر الدولة",
      "Complete your data":"أكمل بياناتك",
      "already have an account ?":"هل لديك حساب ؟",
      "Signin":"تسجيل الدخول",
      "Get Verification Code":"الحصول على رمز التحقق",
      "Enter Verification Code":"أدخل رمز التحقق",
      "Next Step":"الخطوة التالية",
      "Products":"المنتجات",
      "About":"عن",
      "Settings":"إعدادات",
      "Tracking":"التتبع",
      "Name":"الإسم",
      "Email":"الإيميل",
      "Language": "اللغة",
      "English": "الانجليزية",
      "Arabic": "العربية",
      "Logout":"تسحيل الخروج",
      "Save":"حفظ",

      "Home" :"الرئيسية",
      "Categories":"الفئات",
      "Cart":"سلة التسوق",
      "We Care About Your House" : "نحن نعتني بمنزلك",
      "All Categories" : "كل الفئات",
      "Full name" : "الاسم كامل",
      "Age" : "العمر",
      "Country" :"البلد",
      "Address" :"العنوان",
      "Gender" :"النوع",
      "Male" :"ذكر",
      "Female" :"انثي",
      "Cancel" :"الغاء",
      "Done" :"تم" ,
      "Add" :"إضافة",
      "Please Wait Loading" :"برجاء الانتظار جاري التحميل ...",
      "Hello  ": "مرحبا",
      "Client": "عميل",
      "Your Profile" :"ملفك الشخصي",
      "Your Security Information" : "معلوماتك الشخصية المحمية",
      "Change Language" : "تغيير اللغة",
      "Profile": "الملف الشخصي",
      "My Orders" : "طلباتي",
      "Update":"تعديل"
    }
  };
}