class Autogenerated {
  bool? status;
  List<TransportationPeriodData>? data;
  String? message;

  Autogenerated({this.status, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['data'] != null) {
      data = <TransportationPeriodData>[];
      json['data'].forEach((v) {
        data!.add(new TransportationPeriodData.fromJson(v));
      });
    }
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    return data;
  }
}

class TransportationPeriodData {
  int? id;
  int? userId;
  String? from;
  String? to;
  int? active;
  String? createdAt;
  String? updatedAt;
  List<Drivers>? drivers;

  TransportationPeriodData(
      {this.id,
        this.userId,
        this.from,
        this.to,
        this.active,
        this.createdAt,
        this.updatedAt,
        this.drivers});

  TransportationPeriodData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    from = json['from'];
    to = json['to'];
    active = json['active'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['drivers'] != null) {
      drivers = <Drivers>[];
      json['drivers'].forEach((v) {
        drivers!.add(new Drivers.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['from'] = this.from;
    data['to'] = this.to;
    data['active'] = this.active;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.drivers != null) {
      data['drivers'] = this.drivers!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Drivers {
  int? id;
  int? driverId;
  int? transportationPeriodId;
  int? capacity;
  int? active;
  String? createdAt;
  String? updatedAt;
  Driver? driver;

  Drivers(
      {this.id,
        this.driverId,
        this.transportationPeriodId,
        this.capacity,
        this.active,
        this.createdAt,
        this.updatedAt,
        this.driver});

  Drivers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    driverId = json['driver_id'];
    transportationPeriodId = json['transportation_period_id'];
    capacity = json['capacity'];
    active = json['active'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    driver =
    json['driver'] != null ? new Driver.fromJson(json['driver']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['driver_id'] = this.driverId;
    data['transportation_period_id'] = this.transportationPeriodId;
    data['capacity'] = this.capacity;
    data['active'] = this.active;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.driver != null) {
      data['driver'] = this.driver!.toJson();
    }
    return data;
  }
}

class Driver {
  int? userId;
  int? managerId;
  String? createdAt;
  String? updatedAt;
  User? user;

  Driver(
      {this.userId, this.managerId, this.createdAt, this.updatedAt, this.user});

  Driver.fromJson(Map<String, dynamic> json) {
    userId = json['user_id'];
    managerId = json['manager_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['user_id'] = this.userId;
    data['manager_id'] = this.managerId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? name;
  String? email;
  String? phone;
  String? role;
  int? active;
  String? createdAt;
  String? updatedAt;

  User(
      {this.id,
        this.name,
        this.email,
        this.phone,
        this.role,
        this.active,
        this.createdAt,
        this.updatedAt});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    phone = json['phone'];
    role = json['role'];
    active = json['active'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['role'] = this.role;
    data['active'] = this.active;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
